"""LLM release-note generation.

Defined as a swappable interface with a stub implementation. A real provider
(Anthropic Claude, OpenAI, local model) can be wired later behind the same
``LLMReleaseNoteService`` protocol without touching callers.
"""
from __future__ import annotations

from typing import Protocol


class LLMReleaseNoteService(Protocol):
    def draft_release_notes(self, version: str, issues: list[dict]) -> str: ...


class StubLLMProvider:
    """Deterministic, dependency-free draft generator used until a real LLM is wired."""

    def draft_release_notes(self, version: str, issues: list[dict]) -> str:
        stories = [i for i in issues if i.get("type", "").lower() == "story"]
        bugs = [i for i in issues if i.get("type", "").lower() == "bug"]
        lines = [f"# Release Notes — {version}", ""]
        if stories:
            lines.append("## Features")
            lines += [f"- {i.get('key', '')}: {i.get('summary', '')}" for i in stories]
            lines.append("")
        if bugs:
            lines.append("## Bug Fixes")
            lines += [f"- {i.get('key', '')}: {i.get('summary', '')}" for i in bugs]
            lines.append("")
        lines.append("_Draft generated by ReleaseIT (stub LLM). Review before publishing._")
        return "\n".join(lines)


_service: LLMReleaseNoteService = StubLLMProvider()


def get_release_note_service() -> LLMReleaseNoteService:
    return _service
